# site settings
title: 鈴木このみ
subtitle: コールガイド
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://konomi.platinumdis.co" # the base hostname & protocol for your site
font-awesome-icon-logo: fa-music

# homepage tiles
tiles-count: 16

# social settings
twitter_url: https://twitter.com/konomin_call

# build settings
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/
  songs:
    output: true
    permalink: /:path/

sass:
  style: compressed

plugins:
  - jekyll-multiple-languages-plugin

include: [".nojekyll", "CNAME"]
exclude: ["README.md", "phantom_jekyll_theme.gemspec"]

languages: ["ja", "en"]
exclude_from_localizations: ["assets", ".nojekyll"]